name: lactocompanion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  video_player: ^2.9.1
  chewie: ^1.8.1
  share_plus: ^10.0.2
  youtube_player_flutter: ^9.1.2
  url_launcher: ^6.2.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/mother.png
    - assets/images/rategle_logo.png

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21